name: Content Resolver CI

on:
  pull_request:
    branches: [ master ]

jobs:
  setup_and_test:
    runs-on: ubuntu-latest
    container: 
      image: registry.fedoraproject.org/fedora:40
    steps:
    
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Update GPG keys
      run: dnf -y update fedora-gpg-keys
        
    - name: Install git and Python libraries
      run: dnf -y install git-core python3-yaml python3-htmlmin python3-jinja2 python3-koji python3-pytest python3-flake8

    - name: Clean up
      run: dnf clean all

    - name: Create output dir
      run: mkdir -p output/history

    - name: Run the build
      run: ./feedback_pipeline.py --dev-buildroot test_configs output
    
    - name: Run tests
      run: |
        pytest
